version = 1

# Binary and config files that cannot carry inline SPDX headers
[[annotations]]
path = ["logo.png", ".nojekyll"]
SPDX-FileCopyrightText = "2026 ownCloud GmbH - A Kiteworks Company and ownCloud contributors"
SPDX-License-Identifier = "Apache-2.0"
